language: python
sudo: false
python:
- '3.5'
- '3.3'
- '3.4'
- '2.7'
- '2.6'
- pypy
- pypy3
install:
- pip install coveralls
- pip install pep8
script:
- pep8 --exclude test_main.py pygeoif
- coverage run --source=pygeoif setup.py test
after_success: coveralls
notifications:
  email:
  - christian.ledermann@gmail.com
deploy:
  provider: pypi
  user: Chistian.Ledermann
  password:
    secure: TTQcCL3J19iBOdMzOBYdft9XWsV9Ft1GLAzC3nMYX5aQPjB2UHwwvASTUlB8WCpKvDuJfPJxhkh8r2PWT31fyFjskcTwn2Z4WVP5xtt+/qZYu99gf59AxNXjOa+RBPkduVqjBxa+C2y/LcbVd011VmfKV1Usr8a16mf5NsLUjPo=
  on:
    tags: true
    repo: cleder/pygeoif
